version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod

linters:
  default: standard

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
